const ActionTypes = {
  REQ_GET_LOGIN: 'REQ_GET_LOGIN',
  // GET_LOGIN_RESPONSE: 'GET_LOGIN_RESPONSE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',

  REQ_GET_USER: 'REQ_GET_USER',
  GET_USER_RESPONSE: 'GET_USER_RESPONSE',

  ADD_USER: 'ADD_USER',
  ADD_USER_RESPONSE: 'ADD_USER_RESPONSE',
  DEL_USER: 'DEL_USER',
  DEL_USER_RESPONSE: 'DEL_USER_RESPONSE',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_RESPONSE: 'UPDATE_PRODUCT_RESPONSE',

  REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
  GET_PRODUCTS_RESPONSE: 'GET_PRODUCTS_RESPONSE',

  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_RESPONSE: 'ADD_PRODUCT_RESPONSE',
  DEL_PRODUCT: 'DEL_PRODUCT',
  DEL_PRODUCT_RESPONSE: 'DEL_PRODUCT_RESPONSE',

  REQ_GET_PROCAT: 'REQ_GET_PROCAT',
  GET_PROCATS_RESPONSE: 'GET_PROCATS_RESPONSE',
}

export default ActionTypes
